# Generated by Django 5.1.3 on 2024-11-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_conversionhistory_converted_file_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversionhistory",
            name="converted_file_path",
            field=models.CharField(max_length=255),
        ),
    ]
