# Generated by Django 5.1.3 on 2024-11-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_conversionhistory_converted_file_path"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadedfile",
            old_name="upload_date",
            new_name="uploaded_at",
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="docx_metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="pdf_metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
